"""Change user description size

Revision ID: 6b635e85ced6
Revises: aa8490ac5240
Create Date: 2025-07-03 19:30:02.266882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b635e85ced6'
down_revision: Union[str, Sequence[str], None] = 'aa8490ac5240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'description',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.VARCHAR(length=4096),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'description',
               existing_type=sa.VARCHAR(length=4096),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###
